version: "3.9"

services:
  db:
    container_name: db_gps
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "postgres"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    image: postgres:16